"""add invite table

Revision ID: 9e2a4221afea
Revises: a8e86a41f64c
Create Date: 2026-06-25 16:13:17.600596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2a4221afea'
down_revision: Union[str, Sequence[str], None] = 'a8e86a41f64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    # ### end Alembic commands ###
